### PR TITLE
Fix line numbers in error messages

### PR DESCRIPTION
**Pull request by amstrnad**
Make line numbers 1-indexed, rather than 0-indexed.

### CODE REVIEW

**Comment by ccasin** [comment]
I had noticed that things were off by 1, I assume this fixes that?  Can you also run `make parsers` and add the updated `hs` files.  The main build doesn't regenerate the parsers - we commit the generated files to avoid a dependency on `happy` and `alex`.

**Comment by ccasin** [comment]
Thanks.  You can go ahead and merge and update hope-src.  This one doesn't really need CI.

**Comment by amstrnad** [comment]
So merge this, create a pull request on hope-src, and then merge that one?

**Comment by ccasin** [comment]
Yep.  Thanks!

**Pull request merged**
